version: "3"

services:
  server:
    build: server/
    command: python ./server.py
    hostname: echo_server
    environment: 
      - HOST_NAME=echo_server

  client1:
    build: client/
    command: python ./client.py
    volumes:
      - /Users/datumo/Documents/codebase/client-server/client:/client/data
    environment: 
      - CLIENT_ID=1
      - HOST_NAME=echo_server
    depends_on:
      - server

  client2:
    build: client/
    command: python ./client.py
    volumes:
      - /Users/datumo/Documents/codebase/client-server/client:/client/data
    environment: 
      - CLIENT_ID=2
      - HOST_NAME=echo_server
    depends_on:
      - server

  client3:
    build: client/
    command: python ./client.py
    volumes:
      - /Users/datumo/Documents/codebase/client-server/client:/client/data
    environment: 
      - CLIENT_ID=3
      - HOST_NAME=echo_server
    depends_on:
      - server

  client4:
    build: client/
    command: python ./client.py
    volumes:
      - /Users/datumo/Documents/codebase/client-server/client:/client/data
    environment: 
      - CLIENT_ID=4
      - HOST_NAME=echo_server
    depends_on:
      - server

  client5:
    build: client/
    command: python ./client.py
    volumes:
      - /Users/datumo/Documents/codebase/client-server/client:/client/data
    environment: 
      - CLIENT_ID=5
      - HOST_NAME=echo_server
    depends_on:
      - server

